nodejs/TSC

TSC-Charter.md

I know Charter changes need to go through a process, but this is just some minor formatting to make the Definitions section consistent. (Last definition is formatted differently than the first two in the current version of the doc.) So, uh, hopefully it can just sail in.

minor formatting

---

WORKING_GROUPS.md

fixes: https://github.com/nodejs/inclusivity/issues/69

add inclusivity working group

---

Applications/Express.md

The express project is applying to become an incubating top level project.
/cc @nodejs/tsc @Fishrock123 @nodejs/collaborators

Add initial TLP application for express

---

BasePolicies/CONTRIBUTING.md

Talking to @dougwilson in the express thread made me realize that we don't have a simple explanation of our preferred processes that is suitable for simple project.
Now that we're potentially admitting hundreds of individual repos that feed into a single TC I figured it was important to explain the flow of contributions and the governance in a much plainer way.
I also realized that this would make a good starting point for projects in the Node.js Community.

Base Contribution policy.

---

WORKING_GROUPS.md

While reviewing https://github.com/nodejs/nodejs.org/pull/623, I noticed that the list of identity traits was removed from the list of responsibilities for the Inclusivity WG section from [TSC/WORKING_GROUPS.md](https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md) that is present in [inclusivity/README.md](https://github.com/nodejs/inclusivity/blob/master/README.md).
I think this list of identities is important for understanding what this responsibility means, but at the same time I understand how much length it adds to the document and why it was removed.
As a compromise, I added a link to the Inclusivity WG's section on responsibilities so that people can discover the list and the full meaning of this responsibility without bloating the length of this document.

Added link about personal identity

---

BasePolicies/Governance.md
Project-Lifecycle.md
WORKING_GROUPS.md

update DCO to 1.1

---

WORKING_GROUPS.md

TSC Working Groups are called "Top-Level Working Groups".
I also fixed the link to the TSC.

use `Top-Level` Working Groups

---

WORKING_GROUPS.md

Markdown inside markdown!
It is hard to tell that the **Bootstrap** section is a template at first. This PR just adds a code fence around the template section to make it more obvious.
Make sure to hit the "View" button to see how it looks rendered.

put bootstrap template in markdown code fence

---

Moderation-Policy.md

Fill in some ambiguous gaps in the moderation policy
/cc @nodejs/tsc

doc: update the moderation policy

---

meetings/2015-12-03.md
meetings/2016-01-07.md
meetings/2016-01-14.md
meetings/2016-01-21.md
meetings/2016-01-28.md
meetings/2016-02-04.md
meetings/2016-02-11.md
meetings/2016-02-18.md
meetings/2016-03-03.md
meetings/2016-03-10.md
meetings/2016-03-17.md
meetings/2016-03-24.md
meetings/2016-04-07.md
meetings/2016-04-21.md
meetings/2016-05-05.md
meetings/2016-05-19.md
meetings/2016-06-16.md

Ever notice that first line in all the google agenda docs?
> (doc to move to nodejs/node repository after meeting)
...welp, here is a PR to make that happen. I've added in all the video & issue links too. Since (I believe) the google docs are created by copying+paste of an old one, I noticed some things were lingering from the copied version. Often the "Next Meeting" section. So I updated or removed them.

add all meeting minutes to date

---

WORKING_GROUPS.md

In the process of updating the Working Group page for the nodejs.org site, it was brought to my attention that the `WORKING_GROUPS.md` page should also be kept in alignment. This PR is to include these updates.
The original PR can be found here: https://github.com/nodejs/nodejs.org/pull/1012

Update Working Group grammar

---

README.md

In the 2016-11-03 TSC meeting we discussed "who gets access to YouTube" here:
https://www.youtube.com/watch?v=zOLAHZu6HQM&t=3896s
An action item I've had on my TODO list was to document it in the TSC `README.md`... and I've finally gotten to it!

Add info about YouTube access

---

meetings/2017-01-26.md

docs: TSC meeting minutes for 2017-01-26

---

README.md

Let's put the TSC repo under the scope of responsibility for... the TSC 😆

Add the TSC repo to scope

---

README.md

node-report (formerly nodereport) has been renamed, see https://github.com/nodejs/node-report/issues/35#issuecomment-274044126.

Update README.md to reflect node-report rename

---

BasePolicies/CODE_OF_CONDUCT.md
CODE_OF_CONDUCT.md
Moderation-Policy.md
WORKING_GROUPS.md

@nodejs/tsc ... per the discussion and decision at the last TSC call...
Refs: https://github.com/nodejs/TSC/issues/224

meta: move the code of conduct into the TSC repository

---

Member-Travel-Fund.md

Event: Collaborator Summit adjacent to JSConf EU
Location: Berlin, Germany
Amount: USD$ 600
Moved from #234 
> The @nodejs/streams wg face to face to hammer out some of the longer term issues with streams is the primary reason I'd like to be able to go. I work for a small company and while they couldn't cover all of this, they may be able to cover the difference if I only get partial funding.

Add Travel Fund request for calvinmetcalf/collab summit Berlin 2017

---

TSC-Charter.md

@nodejs/tsc:
- Remove expected target size
- Clarify that TSC member is not limited to core project maintainers
- Clarify that the TSC Chairperson is permitted to select delegates to run
regular meetings.
- Add an attendance rule for TSC membership.
Current TSC member vote counts:
/cc @williamkapke

charter: revised membership rules

---

Moderation-Policy.md

Indentation of bullets is not rendering properly. Increasing markdown
indentation from one space to two spaces appears to fix this.

format of moderation policy

---

meetings/2017-03-23.md

docs: meeting minutes 2017-03-23

---

README.md

orangemocha is no longer on TSC, they should no longer be mentioend
as a mentor.
Is the mentor section relevant anymore?

docs: update mentors

---

Member-Travel-Fund.md

Event: Code & Learn event at JSConf.cn 2017
Location: Shanghai, China
From: San Francisco, USA
Amount: US$ 1200
I'd like to reprise my role as a mentor at [Code & Learn at JSConf.cn 2017](https://github.com/nodejs/code-and-learn/issues/68), but my employer is not in a position to cover the travel costs. The amount is an estimate of flights, hotel and visa fees.

Travel Fund request for bengl @ Code & Learn @ JSConf.cn 2017

---

CODE_OF_CONDUCT.md
Moderation-Policy.md

Fixes: https://github.com/nodejs/TSC/issues/261
@nodejs/tsc
/cc @nodejs/collaborators

meta: adopt the contributor covenant CoC

---

Member-Travel-Fund.md

Per conversations with the Board upon requests for an additional allocation to the TSC Travel Fund and a new fund being created for CommComm because the scope may be different, the Board asked that the top-level committees move forward with coordinating a joint fund. This PR lays out the minimal changes I believe is necessary to establish the joint fund. Once merged, we will approach the Board with the new joint allocation request for the remainder of 2017. 
- New allocation $$ amount(TSC amount that needs to be with updated for money spent in the last 2 months and CommComm amount combined)
- Scope of fund–it needs to cover all needs of the project. It currently covers Individual Members. 
- Document coordination and process of admins
**Future to-do for this work:**
- Will also open a new …

Coordinate travel fund across project committees

---

CODE_OF_CONDUCT.md

Many who are looking for a Code of Conduct are often doing so because they've experienced an incident they are considering reporting and they need to see what the process is to do so. Since CODE_OF_CONDUCT.MD is something folks know to look for across projects, but moderation-policy.md is not as much, I've added a little copy and link to this so the process can be found a little easier.

Specify location of moderation guidelines

---

Moderation-Policy.md

@nodejs/tsc @nodejs/community-committee ... this is a *proposed* update to the moderation policy that accomplishes a number of things:
1. It establishes a Moderation Team responsible for enforcement.
* Members of this Moderation Team are selected by *both* the TSC and CommComm.
* The Moderation Team must regularly report all moderation actions to *both* committees.
* All Moderation actions may be overturned only through simple majority vote of *both* committees.
2. It relaxes the 24 hour rule for moderation on collaborator posts
3. It makes changes to the moderation policy the responsibility of both the TSC and CommComm
4. It clarifies temporary 24-hour bans vs. permanent bans
5. It permits the Moderation Team to use GitHub's new Temporary Interaction Limits

meta: moderation policy updates

---

Moderation-Policy.md

Bans are definted as _temporary_ or _indefinite_, but then usage later
on is all about _temporary_ vs. _permanent_. This change makes the
terminology consistent throughout the policy.
Additionally, it re-orders some text so that _temporary_ always appears
before _indefinite_.

Moderation Policy: Use consistent terminology

---

Github-Org-Management-Policy.md

@nodejs/tsc: This is the beginnings of a work-in-progress github organization management policy. The intent is to outline the governance of user roles within the organization, formalization of repository management, and so forth. There have been a number of issues opened (and as yet unresolved) as to who has organization ownership and there have been some recent discussions around this.
Consider this an incomplete proposal for the time being. Input is requested.

meta: github organization management policy

---

TSC-Charter.md

The current board guidelines allow for the Chair and director
to be two different people. The charter has not been updated
to reflect this.
Fixes: https://github.com/nodejs/TSC/issues/332
Refs: https://github.com/nodejs/board/blob/master/by-laws.md#section-54-committees-of-the-members

charter: allow for chair + director to be 2 roles

---

WORKING_GROUPS.md

The acronym TC is used but not defined. If we are referring to the TSC, this patch updates the use of the term consistently throughout the document.

Replace TC with TSC

---

README.md

This has been updated in the main repo but not in the TSC repo

doc: move shigeki to emeritus

---

README.md

AFAIK, we don't do the mentor thing for projects. We can always add this back if it's something we start putting some structure and energy into, but for now, remove it.

remove mentor program: obsolete

---

Strategic-Initiatives.md

Collaborator Onboarding is important, but not a strategic initiative at
this time.

remove collab onboarding from strategic intiatives

---

TSC-Charter.md

Core Projects are not defined anywhere in the Charter. As far as I know,
we do not have Core Project representation as defined in the Charter. We
do not intend to expand the number of Core Projects, and I'm not even
sure we have any at the current time. Remove this material from the
Charter for clarity and concision. (This will require board approval.
Technically doesn't require TSC approval, but that would be nice.)
Removing *Core Projects* from the Charter makes the *Maintainer* terminology superfluous, so that is being removed too. The *Maintainer* terminology is not often used in reference to Node.js in my experience, and when it *is* used. it is synonymous with *Collaborator* and in contradiction with the definition in the Charter. So, again, this removes the *Maintainer* terminology …

remove "Core Projects" and "Maintainer" from charter

---

README.md

Top-level projects do not elect TSC members (and in my opinion should
not but it's a bit of an academic question because tecnically there are
no top-level projects other than core).

remove unused TLP representation on TSC sentence

---

meetings/2018-01-17.md

Lazy copy/paste from GitHub doc. For nits, please contribute directly to branch rather than leaving comments. Using the GitHub interface, it's pretty easy.

minutes for 2018-01-17 meeting

---

Strategic-Initiatives.md

The Moderation Team is spun up and operational. It is now an ongoing
day-to-day activity rather than a strategic initiative. It will still
need to report weekly activity to TSC and CommComm, but it is no longer
necessary to include it in the list of Strategic Initiatives.
By the way, this might be a good opportunity for others to look for items that may no longer need to be treated as strategic.

retire mod team from strategic initiatives

---

README.md

* Remove "top-level projects" second sentence. The information is
covered elsewhere in this doc and in the Project Lifecycle doc. Having
it as the second sentence gives a false sense of the importance of that
aspect of our governance. There is effectively no activity around
top-level projects admission.
* minor style tweaks (add a comma, change date format)

edit README intro

---

GitHub-Org-Management-Policy.md

Neither GitHub terminology nor our own Moderation terminology uses
"ban". We refer to it as "blocking". Update the GitHub management doc
accordingly.

banning -> blocking

---

Strategic-Initiatives.md

Refs: https://github.com/nodejs/TSC/issues/442

doc: linkify names in strategic initiatives

---

GitHub-Org-Management-Policy.md

Refs: https://github.com/nodejs/TSC/issues/257#issuecomment-366847601
cc @Trott

doc: update the repository management policy

---

README.md

Reference: https://github.com/nodejs/TSC/issues/353
Additionally, the [i18n Initiative](https://github.com/nodejs/i18n) from the CommComm has now superseded intl.

Remove intl

---

meetings/2018-03-28.md

Notes for https://github.com/nodejs/TSC/issues/513

doc: add minutes for meeting 28 Mar 2018

---

Strategic-Initiatives.md

As discussed in TSC Meeting, https://github.com/nodejs/TSC/issues/520, move this to the section that needs champions.

Move Async Hooks to section that needs champions

---

meetings/2018-06-20.md

I have no idea why the YouTube recording says Jun 21 🤷‍♀️ .

Add notes for TSC meeting on 2018-06-20

---

BasePolicies/Governance.md

Remove boilerplate governance text indicating that the target size for a
WG is between 6 and 12.
Refs: https://github.com/nodejs/security-wg/issues/364

update boilerplate to remove WG size specifics

---

WORKING_GROUPS.md

Refs: https://github.com/nodejs/post-mortem/issues/48
https://github.com/nodejs/post-mortem has been largely inactive over the last year. I don't believe that's because its activities ceased, rather that the work it was responsible for is happening elsewhere in the organization and, in practice, under the Diagnostics WG. This PR folds the Post-mortem WG into the Diagnostics WG. There were no objections raised in the Post-mortem WG during the nine months since this was proposed in https://github.com/nodejs/post-mortem/issues/48.

meta: fold the Post-mortem WG into Diagnostics WG

---

ONBOARDING.md

I was reading through the ONBOARDING guide and noticed that it was pointing to @mhdawson's fork. Please close if this was intentional.

doc: change links in ONBOARDING.md

---

README.md

https://github.com/nodejs/LTS was renamed to https://github.com/nodejs/Release.
Refs: https://github.com/nodejs/Release/issues/242

update Release WG projects in README.md

---

meetings/2016-04-21.md
meetings/io.js/2014-10-15.md
meetings/io.js/2014-12-10.md
meetings/io.js/2014-12-30.md
meetings/io.js/2015-01-07.md
meetings/io.js/2015-01-13.md

Since I've moved on from NodeSource, I've archived a bunch of meeting recordings that were done under my NS account and put them on the Node.js Foundation account (unlisted so they don't show up in subscribers' feeds). For posterity cause they're probably not going to be preserved in their original location.
FWIW the 2014-10-15 one is the oldest recording available in the non-Joyent series (not sure if there are any recordings from under Joyent). It was when we were still hopeful, doing it as "Node Forward",  just before we gave up and made io.js. There is one earlier, 2014-10-09, but the recording is no longer available. I'm not sure who owned that one, maybe Mikeal or Bert, or why it's no longer available. I haven't watched any of these videos but you can probably watch io.js emerge in …

doc: switch to archived versions of some rvagg meetings

---

TSC-Charter.md

Section 4 says the TSC must meet regularly, but does not determine a frequency. ("weekly" is suggested as an example but not mandated.)
Section 9 then describes the TSC meeting as "weekly". This removes the word "weekly" from section 9.
Charter changes need Board approval so this should not land until the Board approves it.

remove potential conflict in Charter about meeting frequency

---

Strategic-Initiatives.md

I've been spending the past few months on refactoring the bootstrap to pave the way for shipping snapshot (probably created a lot of conflicts for whoever rebases against our master branch but I believe once the refactor reaches a stable state it would be easier to rebase from now on since it'll be less spaghetti-like). Prior to that, I had been working on code cache integration though I am still stuck with build issues, which I plan to solve together with the snapshot integration given how similar the requirements are.
Considering that there is a pretty clear plan for this effort, I think it is worthy of being a strategic initiative of its own. This makes Node.js more viable for tooling, mobile and serverless use cases. (It also does not hurt that this helps us spend less time on waiting …

Create startup performance strategic initiative

---

Strategic-Initiatives.md

I have not been very active on this initiative for a while and will be focusing on other stuff in the foreseeable future so I think I should just remove myself as a champion. If anyone would like to become a new champion for this feel free to push a new commit here or open a follow on PR.
Although IMO the initiative is no longer strategic for us anymore as it's mostly done and the remaining unmigrated errors are all fairly rare. Maybe a more reasonable move is to create a separate section for these inactive (or no longer strategic?) initiatives, or move it to completed (which feels a bit odd since technically it is not completed).

Remove joyee from champions for error migration

---

Strategic-Initiatives.md

From https://github.com/nodejs/build/issues/1154#issuecomment-448418977:
---
Rich and I (Rod) will begin a strategic initiative sometime in January
to do some accounting of resources and costs (people and other) and try
and come up with proposals and plans for reducing pain and improving the
experience for collaborators while managing quality. Or something like
that. Basically we need to think more strategically about this and
understand what our problems and risks are and what we can do about
them.
---
This is that initiative (in April rather than January, but such is
life).

add strategic initiative for Build resources

---

OpenSSL-Strategy.md

This replaces https://github.com/nodejs/TSC/pull/479

doc: describe OpenSSL maintenance strategy

---

ONBOARDING.md

Typically new TSC members will have been invited as observers to TSC
meetings prior to being onboarded. Update the onboarding instructions
to also update the list of observers meeting template.

update ONBOARDING.md for meeting template changes

---

Strategic-Initiatives.md

The OpenSSL policy changed over time:
- https://github.com/nodejs/TSC/issues/364
- https://github.com/nodejs/TSC/pull/479
- https://github.com/nodejs/TSC/pull/677
------
If its not intended that the strategic initiatives point to the most recent PR, please close, but I followed the existing link through a chain of closed issues before it ended at #677 (which landed), so perhaps that's the link that should be in the document?

doc: update link to PR for OpenSSL Policy

---

TSC-Charter.md

Update TSC charter to reflect merged OpenJS foundation.
This cannot land until approved by the Board. (I think we need one final board approval and then subsequent approvals would be by the by the CPC?)

doc: update TSC charter

---

Security-Team.md
WORKING_GROUPS.md

Draft until discussed in https://github.com/nodejs/security-wg/pull/579
2 changes:
doc: describe security team membership
The TSC is directly responsible for security of the Node.js project,
document the responsibilities and the people.
and
meta: modify Ecosystem Security WG charter

meta: modify Ecosystem Security WG charter

---

WORKING_GROUPS.md

The Website working group has not been a functioning working group for
some time. (No meetings, charter is frequently iignored, etc.) It is
effectively a GitHub team and I would like to be able to add and remove
people as appropriate, but I can't do that with a working group. Let's
switch it to a GitHub team. We can always recharter at a later date if
necessary.

decharter website working group

---

README.md

In some cases, the right thing to do was change it to say OpenJS
Foundation. In other cases, the right thing to do was to change it to
say Node.js.
@nodejs/tsc PTAL

remove/update references to Node.js Foundation in README

---

Security-Team.md

Syncing the Triage team membership with the [github team](https://github.com/orgs/nodejs/teams/security-triage/members) results in:
- removals: @cjihrig @mcollina and @rvagg are no longer members
- addition: @shigeki is added as a member
To very clear, this doesn't express an opinion on my part, I'm happy for you all to work on Triage, but we have tooling to sync from github, but not the other way around.
1. Do all the current members of @nodejs/security-triage want to remain on the team?
2. Do any of the documented members, @cjihrig @mcollina @rvagg, want to join the github team?
I added some text to state triage team responsibility:
1. @nodejs/tsc, does that look like a reasonable description of the responsibility?
2. @nodejs/security-triage, do you agree to that responsibility?!
Note …

Clarify security triage team membership and responsibilities

---

Strategic-Initiatives.md

Also, reindented file, some of the tables were wonky.

Remove Python3 strategic initiative

---

ONBOARDING.md

On/offboarding from H1 was missing, it should happen when adding and
removing from the nodejs security team.

doc: on/offboarding from HackerOne

---

Strategic-Initiatives.md

Workers have been stable for a while now, and while there are still PRs being made against the Worker code, the activity does not stand out from other Node.js core areas and I don’t think the feature requires any special handling at this point.
Also, my name was misspelled.

Remove Workers from strategic initiatives

---

meetings/2020-02-05.md

Fixes: https://github.com/nodejs/TSC/issues/810

doc: add minutes for 2020-02-05

---

Strategic-Initiatives.md

* Move N-API to complete
* Move Standards to complete
* Move New Stream APIs to needs mentor
* Remove Mentoring from needs volunters as owned by CommComm
* Remove nsp and modules as modules has an entry and not sure what other
this was covering

doc: update strategic initiatives

---

meetings/2020-03-18.md

doc: add minutes for meeting 18 March 2020

---

meetings/2020-04-16.md

doc: add minutes for meeting 16 April

---

meetings/2020-04-23.md

doc: add minutes for meeting 23 April 2020

---

meetings/2020-04-29.md

doc: Add minutes for meeting 29 April 2020

---

meetings/2020-05-14.md

doc: add minutes from meeting 14 May 2020

---

Security-Team.md

Its indicated by assignment to a group.

doc: describe ready-for-release state

---

Security-Team.md

The existing link is dead (since https://github.com/nodejs/node/pull/23927 renamed the section).
It looks like it is more accurate to say @nodejs/releasers (i.e. the team that can do releases) rather than link to the signing keys.

Fix broken link to release team

---

Security-Team.md

Thanks for all the help so far, HackerOne!

HackerOne is no longer doing Triage for Node.js Core.

---

surveys/promise-rejections/survey.md

Refs: https://github.com/nodejs/TSC/pull/857
@mmarchini

doc: rename warn-with-error to warn-with-error-code

---

WORKING_GROUPS.md

Refs: https://github.com/nodejs/admin/issues/470
Refs: https://github.com/nodejs/package-maintenance/pull/338
[470](https://github.com/nodejs/admin/issues/470) includes the initial request for a separate org under the auspices of the Node.js project and the agreement for that.
[338](https://github.com/nodejs/package-maintenance/pull/338) includes the governance updates which document who the new org will be managed by the package-maintenance WG.

doc: Charter the package-maintenance working group

---

meetings/2020-07-16.md

doc: add minutes for meeting 16 July 2020

---

meetings/2020-09-03.md

doc: add minutes for 3 Sep 2020

---

Security-Team.md

Results of running `ncu-team sync Security-Team.md` from
node-core-utils.

doc: sync Security-Team.md GitHub teams membership

---

meetings/2020-10-01.md

doc: add minutes for meeting 1 Oct 2020

---

WORKING_GROUPS.md

This PR just adds Package Maintenance to the list of WGs for quick navigation.
Also updated `Economic Security` to `Security` as it is listed on the website and in the list for quick navigation

[doc] update list of WG

---

BasePolicies/Governance.md
TSC-Charter.md

There is no reason to use plain HTTP, it only makes things easier to track/hijack for ISPs and other untrustworthy entities.

doc: avoid directing to HTTP if possible

---

Member-Travel-Fund.md

The member travel fund documents were split into multiple documents and the link doesn't work anymore, so it's probably better to link to the repository instead of a non-existing file.

doc: update reference to member travel fund

---

OpenSSL-Strategy.md

The upgrade guide should still be accessible, but it doesn't exist in the most recent versions of Node.js. `66cb29e...` is the last commit that contains it on the main branch.

chore: fix reference to OpenSSL 1.0.2 guide

---

meetings/2020-10-29.md

doc: add minutes for meeting 29 Oct 2020

---

meetings/2020-11-11.md

doc: add minutes for meeting 11 Nov 2020

---

Strategic-Initiatives.md

After many years of work we are marking ESM in Node.js as stable
and sunsetting the Modules Team. Some high level next steps
* Mark modules as stable in core
* Review remaining open issues in nodejs/modules and close / transfer
* Simplify team structure and prune inactive team members
Refs: https://github.com/nodejs/node/pull/35781
Refs: https://github.com/nodejs/modules/issues/567
Refs: https://github.com/orgs/nodejs/teams/modules/discussions/8

strategic initiatives: mark modules as complete

---

meetings/2021-02-04.md

doc: add minutes for Feb 4 2020

---

meetings/2021-02-25.md

doc: add minutes for meeting 25 Feb 2021

---

WORKING_GROUPS.md

I was reading through this doc today and noticed that there was a Markdown link on line [422](https://github.com/nodejs/TSC/blame/main/WORKING_GROUPS.md#L422) that was borked, so I fixed it <3

fix: add missing md link

---

.github/dependabot.yml
.github/workflows/ci.yml
.gitignore
.remarkrc
package-lock.json
package.json

- Setup the remark-lint setup with the Node preset.
- Ignore the currently failing rules
- Add GitHub Actions to check + Depednabot to keep it up-to-date
Doesn't fix any of the existing issues like https://github.com/nodejs/TSC/pull/976 (which would be `remark-lint-no-undefined-references`)

chore: Add remark-lint + CI

---

meetings/2021-04-08.md

doc: add minutes for meeting 8 April 2021

---

meetings/2021-04-22.md

doc: add minutes for meeting 22 April 2021

---

TSC-Charter.md

These updates will require either CPC or Foundation Board approval.
Updates in this commit:
* Resolved an internal conflict in the charter where the minimum
membership was stated to be three members, but a second provision
provides that no more than one-fourth of the members can be affiliated
with the same employer. That second requirement is impossible to meet if
there are only three members. This change resolves that inconsistency by
increasing the  minimum membership to four.
* Remove the indication that the TSC is responsible for the Charter. The
Charter comes from the Foundation Board via the CPC. The TSC is not
self-chartering.
Trivial updates from previous commits that were not run by the board,
but now is a good time to do it:
* The three links in the bottom references were …

updates to TSC charter

---

meetings/2021-07-01.md

doc: add minutes for meeting 1 July 2021

---

WORKING_GROUPS.md

If this is not correct, I guess some additional re-phrasing is required.
If so, please close the PR and I'll make an issue in stead, if appropriate.

Replaced node.js foundation with OpenJS foundation

---

meetings/2021-09-23.md

doc: add minutes for meeting 23 Sep 2021

---

.remarkrc
package-lock.json
package.json

This also updates transitive dependency ansi-regex to 6.0.1.

chore: update remark-preset-lint-node to 3.2.0

---

meetings/2021-10-27.md

doc: add minutes for meeting Oct 27

---

Security-Team.md

cc @nodejs/tsc 
New volunteers would be highly welcomed.

Updated security team to reflect the status quo

---

Security-Team.md

The list is out of date. Update it with the members of @nodejs-private/security.

chore: update list of people with access to private repo

---

Security-Team.md

`its` is possessive. `it's` is intended here, but switching it to `it is` for even more certainty.

chore: fix typo in Security-Team.md

---

votes/2021-09-29-0.json
votes/2021-10-19-0.json
votes/README.md

This is a final step before being able to automate the identification of
inactive TSC members per the charter.

add initial vote data

---

Security-Team.md

There is a missing _is_ in the existing sentence, but this rewords it a bit.

chore: fix minor grammar typo in Security-Team.md

---

meetings/2021-11-17.md

doc: add minutes for meeting 17 Nov

---

.github/dependabot.yml

This is a super-minor thing, but my YAML linter complains about the
indentation in dependabot.yml and I think this is "better".

chore: fix indentation in dependabot.yml

---

WORKING_GROUPS.md

There is a mistranslation about 'Korean' in WORKING_GROUPS.md.
[nodejs-ko](https://github.com/nodejs/nodejs-ko) is the community in Republic of Korea,
but 조선말 means North Korean. It's a different country.
For reference, 'Korean' had been translated as [한국어](https://github.com/nodejs/nodejs.org/blob/88f8ca74c67b439aca43b456162694028622bd35/locale/en/about/working-groups.md?plain=1#L147) in [nodejs.org](https://github.com/nodejs/nodejs.org).
- [Related issue in nodejs.org](https://github.com/nodejs/nodejs-ko/issues/344)
- [Related commit in nodejs.org](https://github.com/nodejs/nodejs.org/commit/bede521bde283fadea94b291b74ffb0d8dac3435)

chore: fix mistranslation in WORKING_GROUPS.md

---

meetings/2022-02-10.md

Closes: https://github.com/nodejs/TSC/issues/1162

doc: add minutes for meeting 10 Feb 2022

---

README.md
Security-Team.md
Strategic-Initiatives.md

`doc/guides` was moved to `doc/contributing` in
https://github.com/nodejs/node/pull/41408.
Signed-off-by: Darshan Sen <raisinten@gmail.com>

doc: fix core repo `doc/guides` links

---

meetings/2022-02-16.md

Closes: https://github.com/nodejs/TSC/issues/1166

doc: add minutes for meeting 16 Feb 2022

---

meetings/2022-03-10.md

doc: add minutes for 10 Mar 2022

---

OpenSSL-Strategy.md

Refs: https://github.com/nodejs/TSC/issues/1207

doc: update outdated OpenSSL 3.x strategy

---

meetings/2022-05-25.md

doc: add minutes for meeting 25 May 2022

---

meetings/2022-06-01.md

Meetings notes for 2022-06-01

---

Security-Team.md

Ran `ncu-team sync Security-Team.md` after removing myself from the
relevant GitHub teams.

chore: remove Trott from triage team

---

meetings/2022-07-13.md

~Could someone add the recording URL?~ (Thanks, @RaisinTen!)

chore: add minutes for today's TSC meeting

---

Streaming/Streaming-To-Youtube.md

It looks like we changed the email for logging in with the Zoom account
but that change wasn't properly documented in the Streaming-To-Youtube
guide.

chore: fix zoom email on streaming guide

---

meetings/2022-09-07.md

doc: add minutes for meeting 7 Sep 2022

---

meetings/2022-10-19.md

Our tooling depends on this header so we should land this quickly before the find-inactive-folks job runs and wrongly flags James again. The heading structure of the minutes is wrong without it anyway. Announcements should not be a sub-header of Present.

fix: add missing header in minutes doc

---

TSC-Charter.md

Voting to add new members or to ask the CPC for charter changes is unnecessary if there is consensus. We have, to my knowledge, never actually needed a vote on either of these things. In all cases, consensus would have been sufficient, but votes were required by the charter.

remove unnecessary vote requirements from charter

---

meetings/2022-12-14.md

doc: add minutes for meeting 14 Dec 2022

---

meetings/2023-01-18.md

Signed-off-by: Matteo Collina <hello@matteocollina.com>
Fixes #1331

Added minutes of 2023-01-18 meeting

---

WORKING_GROUPS.md

Hello 👋
Updating the `WORKING_GROUPS.md` file following recommandation of @mhdawson in the following issue: https://github.com/nodejs/security-wg/pull/874
I've made the same changes:
- remove reference to legacy nsp (Node Security Project) which was acquired by npm inc. (which was then acquired by GitHub)
- remove "ecosystem" prefix for the WG as this has been promoted & is canonically known as Node.js's "Security WG"

Update Security Working Group

---

WORKING_GROUPS.md

It seems that the working group can function as a GitHub team.
Closes: https://github.com/nodejs/TSC/issues/1081

decharter Ecosystem Security Working Group

---

meetings/2023-03-22.md

I don't see the recording at https://www.youtube.com/@nodejs-foundation/streams. Maybe we didn't stream today's meeting? I left the recording blank in the minutes. Please update to indicate either the URL of the recording or a few words to say it wasn't streamed. Then pull it out of draft mode. Thanks!

add minutes for March 22 2023 meeting

---

WORKING_GROUPS.md

See https://github.com/nodejs/TSC/issues/1027, Nan team is not operating as a working group more as a team.

Convert api working group to addon team

---

meetings/2023-09-13.md

Fixes https://github.com/nodejs/TSC/issues/1437

Added minutes for 2023-09-13

---

meetings/2023-11-08.md

Fixes: https://github.com/nodejs/TSC/issues/1468
@richardlau @ronag @aduh95 - feel free to edit the minutes, I noted a few things from my memory, and some copied from the chat, so may or may not be formatted

doc: add minutes for meeting 8 nov 2023

---

meetings/2023-11-29.md

Fixes https://github.com/nodejs/TSC/issues/1476

Added minutes for 2023-11-29 meeeting

---

ONBOARDING.md

The `crypto-export` mailing list is no longer used and is being removed.
Refs: https://github.com/nodejs/email/pull/238
Refs: https://github.com/nodejs/admin/pull/617

doc: remove references to `crypto-export` list

---

.github/workflows/closeVote.yml
.github/workflows/initiateNewVote.yml
.github/workflows/watchVote.yml
votes/initiateNewVote/README.md
votes/initiateNewVote/_EDIT_ME.yml
votes/initiateNewVote/decryptPrivateKeyAndCloseVote.mjs
votes/initiateNewVote/extractInfoFromReadme.mjs
votes/initiateNewVote/generateNewVotePR.mjs
votes/initiateNewVote/getVoteStatus.mjs

This PR adds automation and documentation for vote initialisations, it adds automation to report invalid vote commits, and to close votes.
Code reviews are welcome, note that we should wait for the transfer of Caritat npm package to the `@node-core` scope to be completed before landing.
Blocked on: https://github.com/nodejs/node-core-utils/pull/704
Fixes: https://github.com/nodejs/TSC/issues/1165

Add vote lifecycle workflows and scripts

---

votes/initiateNewVote/_EDIT_ME.yml

Requesting vote due to the blockers of pull-request https://github.com/nodejs/node/pull/52459.
Currently, there are 4 blockers (2 TSC members) and 6 approvals (5 TSC members) in the original pull-request.
cc @nodejs/tsc

Request for vote to reduce inactive collaborator duration

---

meetings/gen-meeting.sh

This adds the script I used to generate the PR from the google doc after meetings.  You need to be in the meetings directory of a copy of the TSC repo that was checked out. The parameter is the GUID like value in the google meeting doc link.
Adding so that I don't lose it and so other people who Chair TSC meetings can use if they want to as well.

doc: add script used to generate PR for minutes

---

.github/workflows/ci.yml
.github/workflows/initiateNewVote.yml

Given we don't need any specific Node.js version in these workflows, we can use the already installed version (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) and get slightly faster CI and fewer things to keep up-to-date.

Remove `actions/setup-node`

---

votes/initiateNewVote/_EDIT_ME.yml

Refs: https://github.com/nodejs/TSC/issues/1575#issuecomment-2166976221

Propose vote to unblock `--env-file` PRs

---

package-lock.json

`npm ci && npm run test` will now report the line/column numbers for trailing spaces.

chore: update package-lock dependencies

---

votes/initiateNewVote/_EDIT_ME.yml

This is a follow-up to the naming bikeshed in https://github.com/nodejs/loaders/issues/221 which is for the implementation in https://github.com/nodejs/node/pull/54563 A summary can be found in https://github.com/nodejs/node/pull/54563#pullrequestreview-2288424604

Start a vote on require(esm) markers

---

.github/workflows/closeVote.yml

There's a discrepancy in the file causing the workflow to fail https://github.com/nodejs/TSC/blob/2fb3417f6893d04adb8a00f66521eb812c6d9789/.github/workflows/closeVote.yml#L57

fix(votes): typo in `closeVote.yml`

---

TSC-Charter.md

Some people mighrt be contracted to work on OSS on behalf of companies. This does not make them _less_ affiliated, and it might be used to circumvent the affiliation rules.

Clarify the Charter so that contractors are explicity counted as affialiated

---

votes/initiateNewVote/_EDIT_ME.yml

@nodejs/tsc ... as discussed on this TSC call today. Initiate a formal vote on the corepack discussion

Open Corepack Vote

---

ONBOARDING.md

Currently, our offboarding instructions does not indicate to remove "ownership" over the pkgjs org, probably relying on the next instructions that tells to remove them from the org altogether. However, there's an exception, they might member of pkgjs for another reason then TSC membership, in which case we should probably change their role to Member.
I've also changed the order a bit to give less work when offboarding (if you start by removing the member from the org, you don't need to change the role or remove them from the team)

Update offboarding instructions

---

TSC-Charter.md

I've considered adding requirements regarding what tool to use, but after giving it some more thoughts, it's probably better if the choice of the tool is not chartered so if we need/want to change it, it doesn't require CPC approval. Instead, let's edit the charter so it forbids the use of a voting solution that would lack the features we deem important:
- The wording around how the "winner" is defined currently seems to assume there would be always two candidates. Although the current wording is not invalid for many-candidate votes depending how one define the word "vote", it makes more sense to write it in a way that assume there might be more than two candidates.
- Added a sentence that requires ballots not to be disclose before the vote closes. It's been a few years we've operated …

doc: update charter section on voting

---

WORKING_GROUPS.md

Remove `Addon API` working group from the outline list.
Ref: https://github.com/nodejs/TSC/commit/d8d7cb2c630a42f2974fef1edc837d95478df1f1

Remove Addon API working group

---

TSC-Charter.md

~The only effect of this change should be that TSC regular members participate in lazy consensus process~ EDIT: this has been removed, this PR should not have any effect for regular members. If you see another effect that I overlooked, that's not on purpose, so please chime in.
The aim of this change is to clarify that TSC voting members do not have any specific powers (except the ones defined by the Moderation Policy and the ones delegated by the TSC on a case by case basis) over Collaborators.

Update charter to concentrate responsibilities on the TSC rather than its voting members

---

meetings/2025-07-30.md

Signed-off-by: Matteo Collina <hello@matteocollina.com>

Add minutes for 2025-07-30

---

meetings/2025-08-06.md

Fixes https://github.com/nodejs/TSC/issues/1774

docs: minutes for 2025-08-06
