nodejs/TSC

- Member-Travel-Fund.md
Based on feedback from the last board session I've drafted a fund for members to travel and promote the foundation.
This is based mostly on input from @danese on a fund the Apache Foundation had early on and on conversations with @indexzero and @rvagg
> Travel fund for foundation members.

- README.md
It was broken and misspelled :)
> Update link to Project Lifecycle

- Applications/libuv.md
A few notes:
* This will have to be supported by the current libuv maintainers.
* Merging this will mean the TSC endorses the application, it will then need to be included in a board resolution in order to be admitted.
Shortly after opening this PR I will cross post to the libuv issue tracker.
> Application for libuv to enter the incubator.

- meetings/2016-06-30.md
- meetings/2016-07-14.md
Please review. It would be nice to get a cadence of accepting these regularly.
> 2016-06-30 and 2016-07-14 meeting minutes

- README.md
Update TSC member list following orangemocha's resignation.
> Remove orangemocha from TSC members

- meetings/2016-10-20.md
Original at https://docs.google.com/document/d/1c8KaYJHnSVNQeEVyFdnK4J7PbH_LnR-NpG_YUGUftB8.
/cc @nodejs/tsc
> doc: add TSC meeting minutes for 2016-10-20

- meetings/2016-11-02.md
As the title says.
/cc @nodejs/tsc
> doc: add TSC meeting minutes for 2016-11-02

- meetings/2016-11-17.md
> doc: add TSC meeting minutes for 2016-11-17

- meetings/2016-12-15.md
> doc: add TSC meeting minutes for 2016-12-15

- meetings/2016-10-06.md
Looks like this one got missed
> doc: add TSC meeting minutes for 2016-10-06

- meetings/2017-01-12.md
> docs: add TSC meeting minutes 2017-01-12

- Member-Travel-Fund.md
Updating the total cost of the reimbursement for NINA 2016
> doc: Fixing Italo A. Casas travel found for NINA 2016

- meetings/2017-02-09.md
> docs: add TSC meeting notes 2017-02-09

- README.md
Add joshgav to the list of TSC members. Also need to be added to GH groups.
> docs: add joshgav

- Member-Travel-Fund.md
Event: Collaborator Summit adjacent to JSConf EU
Location: Berlin, Germany
I’ll be attending the collaborator summit in Berlin, and don’t have an employer to cover my costs. Since on the global scale I’m not living so terribly far away, $ 240 should be enough to cover all travel costs. :)
> Travel Fund Request: Anna Henningsen, May 2017 Collaborators Summit

- WORKING_GROUPS.md
Per: https://github.com/nodejs/TSC/issues/218
> meta: decharter inclusivity wg

- Member-Travel-Fund.md
Event: Collaborators Summit adjacent to JSConf EU
Location: Berlin, Germany
From: Geneva, Switzerland
Amount: US$ 318
I will be attending the collaborators summit in Berlin and my employer is not going to cover the costs. I have already booked airplane tickets and lodging. The total cost is US$ 318.
> Travel Fund Request: Michaël Zasso, May 2017 Collaborators Summit

- Member-Travel-Fund.md
The amount is not final yet, the exact value may decrease, but the estimated upper bound is €680.
_@mikeal suggested to specify the amount in EUR as both the visa fee and lodging are in EUR_.
I will be travelling from Moscow, Russia.
* Travel tickets are about €230-€360 atm + €16.
* Lodging for 3 nights was €211 (I already booked it).
* Visa fee should be under €90 (not exactly sure which category yet).
I will also probably need an invitation for the travel visa.
> Travel Fund Request: Никита Сковорода, May 2017 Collaborators Summit

- Member-Travel-Fund.md
Event: Collaborators Summit adjacent to JSConf EU
Location: Berlin, Germany
From: Madrid, Spain
Amount: US$ 160
I'd like to ask for a fund to cover the flight costs to attend the Collaborator Summit. My employee won't cover the costs. Cost is approximate.
> Add Travel Fund request for santigimeno/collab summit Berlin 2017

- README.md
I won't have as much time going forward and I want to focus what time I
have on technical matters.  I'll remain a member of the CTC.
> doc: step down from the TSC

- README.md
> doc: add Myles to TSC membership list

- Member-Travel-Fund.md
Event: Collaborators Summit @ Node.js Interactive North America 2017  
Location: Vancouver, BC, Canada  
From: Los Angeles, CA, United States  
Amount: US$ <del>1400</del> 1200
I'm going to attend the Collaborators Summit in Vancouver in October. I don't have an employer right now, so I'd like to ask for funding for transportation to/from and lodging at the event. The $1400 I put in the document is an approximation, but the actual costs will almost certainly be lower.
> Add Travel Fund request for @TimothyGu at Oct 2017 Collab Summit

- Member-Travel-Fund.md
Event: Collaborator's Summit at NINA 2017
Location: Vancouver, BC, CA
From: Hanover, Germany
Amount: €1300 (approx.)
I would like to attend the Collaborator's Summit in October and to mentor at C&L as suggested by @addaleax. Being a full-time student, I don't have an employer who will cover travel and lodging, therefore I would like to ask for funding. The specified amount is an approximation, resulting from railway from Hanover to Frankfurt, flight to Vancouver (prices changing daily) and lodging.
> Add Travel Fund request for @tniessen at Oct 2017 Collab Summit

- Moderation-Policy.md
> fix minor formatting problem in Moderation Policy

- README.md
Refs: https://medium.com/@mylesborins/effective-immediately-i-am-stepping-down-from-the-nodejs-tsc-3df37c6ccbae
> meta: remove MylesBorins from TSC membership list

- README.md
TSC is largely defunct, ineffective, unrepresentative, and I do not believe it will recover on its own.
> meta: remove fishrock123 from TSC membership list

- Member-Travel-Fund.md
Event: Collaborator's Summit at NINA 2017
Location: Vancouver, BC, CA
From: Belo Horizonte, Brazil
Amount: €1500 (approx.)
I would like to attend the Collaborator's Summit in October and to also mentor at C&L. Sadly my employer is not in a position to cover the costs, therefore I would like to ask for funding. The specified amount is an approximation, resulting from my flight from Belo Horizonte to Vancouver (prices changing daily) and lodging.
I would also love to attend the Node.js Interactive and was wondering if there is any possibility to attend that for free (covering for costs that the foundation would get back through the ticket price would be weird somehow).
> Travel Fund request for @BridgeAR at Oct 2017 Collab Summit

- README.md
Includes the changes from https://github.com/nodejs/node/pull/15722
> meta: sync members list with nodejs/node

- README.md
- WORKING_GROUPS.md
Ref: https://github.com/nodejs/TSC/issues/353
> remove dechartered Intl working group

- meetings/node.js/2017-12-20.md
Glorious copy/paste from the Google doc. Direct editing of this PR/branch encouraged.
> add minutes for 12-20-2017 meeting

- README.md
> remove list duplication

- Strategic-Initiatives.md
Not sure if we need to keep track of completed initiatives, but if we're
doing it, might as well add the Moderation Team.
> update completed initiatives

- meetings/node.js/2018-03-14.md
lazy copy/paste,  please push nits/corrections/additions directly to the branch if possible, thanks
> add minutes for 2018-Mar-14 meeting

- Strategic-Initiatives.md
Also adds the link to the tracking issue for migrating
C++ errors into JS.
I have discussed this with @mhdawson who asked @jasnell
> Update Joyee Cheung as the champion for error messages

- meetings/2018-04-18.md
Minutes for https://github.com/nodejs/TSC/issues/520.
> doc: add minutes for 18 April 2018

- Strategic-Initiatives.md
If https://github.com/nodejs/node/pull/21594 lands we can spin down this initiative
> strategic-initiatives: add pr to track npm initiative

- ONBOARDING.md
Fixes: https://github.com/nodejs/TSC/issues/524
> add onboarding/offboarding doc

- README.md
Refer people to the Charter for details.
> make README introduction more concise

- Strategic-Initiatives.md
Policy has landed in nodejs/node 🎉
> doc: move npm initiative to completed

- Strategic-Initiatives.md
I agreed last week to add myself to Governance and share it with @MylesBorins due to our combined interest in the shared values discussion.
> doc: add Rod to Strategic Initiatives / Governance

- Strategic-Initiatives.md
I've been the primary person on this pretty much since it started, and this updates the links to actually relevant places.
> doc: update streams api initiative

- README.md
Cosmetic fix to remove an extraneous closing bracket in the README
> fix: extraneous closing bracket

- Strategic-Initiatives.md
This reverts commit dff568bcca15c4db9a1d12608f4308f478e2bddc.
> Revert "doc: add Rod to Strategic Initiatives / Governance (#584)"

- meetings/2018-12-05.md
Fixes https://github.com/nodejs/TSC/issues/637
> Minutes for meeting 2018-12-05

- meetings/2019-02-14.md
Fixes https://github.com/nodejs/TSC/issues/664
> Added minutes for 2019-02-14.

- Strategic-Initiatives.md
I'm happy to be the Champion for the core promises API.
cc @jasnell
> Replace @jasnell as Champion for core promises API

- Strategic-Initiatives.md
Work has been underway on a QUIC protocol implementation for core.
> Add QUIC as a strategic initiative

- Strategic-Initiatives.md
* Move OpenSSL Evolution to complete
* Move Async Hooks to needs-champion
* Remove Rod (but leave Rich) for Build Resources
> updates to strategic initiatives

- Streaming/Streaming-To-Youtube.md
> doc: update streaming docs

- Strategic-Initiatives.md
as discussed in today's meeting
> doc: move governance to completed

- Security-Team.md
/cc @mralekzandr @nodejs/security
> doc: describe security workflow

- meetings/2020-02-26.md
> doc: add minutes for meeting 26 feb 2020

- meetings/2020-03-11.md
> doc: add minutes for 11 March 2020

- meetings/2020-04-01.md
> doc: Add minutes for 1 April 2020

- meetings/2020-04-08.md
> doc: add minutes for meeting 8 April 2020

- meetings/2020-05-07.md
> doc: add minutes for meeting 7 may 2020

- meetings/2020-06-04.md
> doc: add minutes for meeting 4 June 2020

- meetings/2020-07-09.md
> doc: add minutes for meeting 9 July 2020

- meetings/2020-07-02.md
> doc: add minutes for meeting 2 July 2020

- meetings/2020-08-06.md
Closes: https://github.com/nodejs/TSC/issues/900
> doc: add meeting notes of 2020-08-06

- meetings/2020-08-13.md
> doc: add minutes for meeting 13 Aug 2020

- meetings/2020-08-27.md
> doc: add minutes for meeting 27 Aug 2020

- ONBOARDING.md
Refs: https://github.com/nodejs/admin/issues/470
> doc: add onboarding step for pkgjs org

- meetings/2020-09-24.md
> doc: add minutes for meeting 24 Sep 2020

- meetings/2020-10-08.md
> doc: add minutes for meeting 8 Oct 2020

- WORKING_GROUPS.md
Add permalink https://github.com/nodejs/i18n to section title of `i18n`.
> doc: add i18n link

- README.md
- WORKING_GROUPS.md
> doc: de-charter benchmarking WG

- meetings/2020-12-09.md
> doc: add minutes for meeting 9 Dec 2020

- meetings/2021-01-14.md
> doc: add minutes for meeting 14 Jan 2021

- meetings/2021-03-18.md
> doc: add minutes for meeting 18 march 2021

- meetings/2021-03-18.md
@mhdawson just a small race between the 2 PRs landing. Throwing the quick fix while you get your local setup for the next round :smile:
> fix: literal urls in 2021-03-18.md

- meetings/2021-03-25.md
> doc: add minutes for meeting 25 march 2021

- OpenSSL-Strategy.md
We'll have to update this anyway for +quic.
> Improve wording in OpenSSL-Strategy

- .github/workflows/ci.yml
- .github/workflows/remark-lint-problem-matcher.json
Pulled from nodejs/node so there are inline comments on the Files tab of a PR for affected lines
> chore: Add remark-lint problem matcher

- meetings/2021-04-15.md
> doc: add minutes for meeting 15 April 2021

- meetings/2021-04-29.md
> doc: add minutes for meeting 29 Apr 2021

- README.md
Mostly fixing typos and conforming with style guide. Remove some
material that doesn't really apply anymore. (OpenJS Foundation Board
shouldn't and doesn't talk to the TSC about admitting new projects like
the Node.js Foundation Board might have.)
> chore: edit README.md

- meetings/2021-05-20.md
> doc: add minutes for meeting 20 May

- meetings/2021-06-10.md
> doc: add minutes for meeting 20 June 2021

- meetings/2021-07-14.md
> doc: add minutes for meeting 14 July 2021

- meetings/2021-06-23.md
> doc: add minutes for meeting 23 June

- meetings/2021-07-22.md
> doc: add minutes for July 22 2021

- meetings/2021-07-29.md
> doc: add minutes for 29 July 2021

- meetings/2021-08-25.md
> doc: add minutes for meeting 25 Aug 2021

- meetings/2021-11-04.md
> doc: add minutes for meeting 4 Nov 2021

- CODE_OF_CONDUCT.md
The target branch is visible and should be changed.
> Update target branch in Code of Conduct

- Security-Team.md
In consultation with folks at the security triage meeting, here are some triage workflow updates.
> doc: update triage workflow

- meetings/2021-12-02.md
> doc: add minutes for meeting 2 Dec 2021

- meetings/2021-12-16.md
> doc: add minutes for meeting 16 Dec 2021

- meetings/2022-01-06.md
> doc: add minutes for meeting 6 Jan 2022

- meetings/2022-01-13.md
> doc: add minutes for meeting Jan 13 2022

- meetings/2022-01-19.md
Fixes: https://github.com/nodejs/TSC/issues/1152
> doc: add minutes for meeting jana 19th 2022

- meetings/2022-01-26.md
> doc: add minutes for meeting 26 Jan 2022

- meetings/2022-02-03.md
> doc: add minutes for meeting 3 Feb 2022

- ONBOARDING.md
Refs: https://github.com/nodejs/node/issues/33864
> doc: update links in ONBOARDING to new branches

- meetings/2022-02-23.md
> doc: add minutes for meeting 23 Feb 2022

- meetings/2022-03-03.md
> doc: adminutes for meeting 3 March 2022

- ONBOARDING.md
Ref: https://github.com/nodejs/TSC/issues/1133#issuecomment-1076786899
> doc: add Google Group instructions to onboarding

- meetings/2022-03-23.md
> doc: add minutes for meeting 23 March 2022

- WORKING_GROUPS.md
see: https://github.com/nodejs/security-wg/pull/789
Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>
> doc: remove Node.js Ecosystem HackerOne program references

- meetings/2022-03-31.md
> doc: add minutes for meeting 31 March 2022

- .github/dependabot.yml
- .github/workflows/ci.yml
Make the YAML files comply with the requirements of `make lint-yaml` in
the core repo.
> chore: update YAML files to comply with core lint requirements

- meetings/2022-04-06.md
> doc: add minutes for meeting 6 April 2022

- meetings/2022-04-20.md
Fixes: https://github.com/nodejs/TSC/issues/1212
> doc: add minutes for meeting April 20 2022

- Security-Team.md
> doc: add RafaelGSS to Security Team (patches/reports)

- meetings/2022-04-27.md
> doc: add minutes for meeting 27 Apr 2022

- meetings/2022-05-04.md
> doc: add minutes for meeting May 4 2022

- meetings/2022-05-11.md
Signed-off-by: Matteo Collina <hello@matteocollina.com>
> Add Minutes for TSC Meeting 2022-05-11

- meetings/2022-05-18.md
> doc: add minutes for meeting 18 May 2022

- meetings/2022-06-15.md
> doc: add minutes for meeting 15 June 2022

- meetings/2022-06-22.md
> Meeting of the 2022-06-22

- meetings/2022-06-29.md
> doc: add minutes for meeting June 29 2022

- votes/2022-07-06.json
I linked to the wrong issue in this JSON file originally.
> fix: use correct URL in vote file

- meetings/2022-07-06.md
> doc: add minutes for meeting 6 July 2022

- meetings/2022-07-20.md
> doc: add minutes for meeting 20 Jul 2022

- meetings/2022-07-27.md
> doc: add minutes for meeting 27 Jul 2022

- meetings/2022-08-03.md
Fixes: https://github.com/nodejs/TSC/issues/1266
> doc: add minutes for meeting 03 Aug 2022

- meetings/2022-08-10.md
Refs: https://github.com/nodejs/TSC/issues/1268
> chore: add minutes for 10-Aug-2022 meeting

- votes/2022-09-15-0.json
> chore: add vote for adding TSC member

- meetings/2022-09-21.md
> doc: add minutes for meeting 21 Sep 2022

- meetings/2022-09-28.md
> doc: add minutes for meeting Sep 28 2022

- meetings/2022-10-12.md
> doc: add minutes for meeting 12 Oct 2022

- meetings/2022-10-19.md
> doc: add minutes for meeting Oct 19 2022

- meetings/2022-11-02.md
> doc: add minutes for meeting 2 Nov 2022

- meetings/2022-11-09.md
> doc: add minutes for meeting 9 Nov 2022

- meetings/2022-11-23.md
> doc: add minutes for meeting Nov 23 2022

- votes/2022-11-30-0.json
Fixes: https://github.com/nodejs/TSC/issues/1308
> add vote data for RafaelGSS nomination

- meetings/2022-11-30.md
> doc: add minutes for meeting 30 Nov 2022

- meetings/2022-12-07.md
Signed-off-by: Matteo Collina <hello@matteocollina.com>
Fixes #1317
> Add meeting notes for 2022-12-07

- Nodejs-Bug-Bounty-Security-Fund.md
> doc: add governance for LFX Crowdfunding account

- meetings/2022-12-21.md
> doc: add minutes for meeting 21 Dec 2022

- meetings/2023-01-04.md
> doc: add minutes for meeting 4 Jan 2023

- meetings/2023-01-11.md
> doc: add minutes for meeting 11 Jan 2023

- meetings/2023-01-25.md
> doc: add minutes for meeting 25 Jan 2023

- meetings/2023-02-01.md
> doc: add minutes for meeting Feb 1 2023

- WORKING_GROUPS.md
Ref: https://github.com/nodejs/admin/issues/784#issuecomment-1511821170
> remove i18n Working Group

- meetings/2023-05-24.md
> Added minutes for 2023-05-24.md

- Security-Team.md
Current list and link is wrong. This reflects current state.
> chore: update HackerOne membership

- meetings/2023-07-26.md
> Meeting 2023 07 26

- meetings/2023-09-06.md
Fixes https://github.com/nodejs/TSC/issues/1434
> Added minutes for 2023-09-06

- meetings/2023-09-27.md
Fixes https://github.com/nodejs/TSC/issues/1442
> Added minutes for 2023-09-27

- ONBOARDING.md
I can't access that link, but I've been told it's supposed to be this one.
> doc: fix link in `ONBOARDING.md`

- meetings/2024-02-07.md
Fixes https://github.com/nodejs/TSC/issues/1500
> Meeting notes for 2024-02-07

- Moderation-Policy.md
The existing link redirects, so not exactly a fix, but let's update it anyway.
> chore: update Moderation Policy location

- votes/2024-05-07-0.json
To be consistent with the other vote summary – and to fit our automations.
> fix: use GitHub handle in `votes/2024-05-07-0.json`

- votes/initiateNewVote/README.md
The documentation was lacking, I figured I might as well add it.
> document how to close a vote

- meetings/2024-08-14.md
Fixes https://www.youtube.com/watch?v=EMqANecYmHs
(Sorry for the long delay, things have been busy)
> Add meeting notes for 2024-08-14

- meetings/2024-12-18.md
Fixes https://github.com/nodejs/TSC/issues/1665
> Add minutes for 2024-12-18

- meetings/2025-04-09.md
> doc: add 2025-04-09 meeting minutes

- meetings/2025-06-11.md
> minutes for 2025-06-11

- votes/initiateNewVote/_EDIT_ME.yml
Refs: https://github.com/nodejs/TSC/issues/1763
> Open vote to elect the Vice-Chair(s) of the TSC
